### ISSUE TITLE
Error, after install

### ISSUE THREAD

**Issue by mihailbishkek** [eXpl0it3r/oc-menu-reorder#4]
I have error, after install on link: backend/lukas/menureorder/menu/reorder 

![default](https://user-images.githubusercontent.com/18412931/51437171-a5a91480-1cc4-11e9-8757-34eed3fe50f9.JPG)

**Comment by eXpl0it3r** [comment]
I'm so sorry for my 1.5 year delay in responding here. For some reason I wasn't watching my own repository anymore and thus didn't receive any notification about issues...

I've added a default value for the sort_order column as suggested in #5 and implemented with commit 86f9962dbf638e23d36cf528eddccff682646c1c
The new 1.0.1 version holds that fix: https://octobercms.com/plugin/lukas-menureorder
